name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python:
        - pypy3
        - 3.6
        - 3.9
        - "3.10"
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install "tox<3.27.0"
      - name: Run tests
        run: tox -v -- --cov-report xml
      - name: Publish coverage
        if: false  # disabled for #2727
        uses: codecov/codecov-action@v1
        with:
          flags: >-  # Mark which lines are covered by which envs
            ${{ runner.os }},
            ${{ matrix.python }}

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: 3.9
      - name: Install tox
        run: |
          python -m pip install "tox<3.27.0"
      - name: Release
        run: tox -e release
      - uses: "actions/upload-artifact@v4"
        with:
          name: artifacts
          path: ./dist/*
